### ISSUE TITLE
Do you have the JSON data behind the Rig Veda API available?

### ISSUE THREAD

**Issue by lancejpollard** [AninditaBasu/indica#7]
I saw that you took down the API after Heroku free plan stopped, that's too bad. Do you happen to have the data you used, or know of a place that has such rich data? I would love to use and play around with it!

**Comment by AninditaBasu** [comment]
Not only did Heroku stop the free plan but it also refused to sign me up for the Basic plan when I tried. Now, it doesn't even let me log in without MFA (and I don't have a  Heroku-acceptable verification method). Have to really find an alternative.

To answer your question, yes, I have the data 🙂 It's in a private repo here. Would you want me to add you to the repo? I'd love to see what you'll use the data for. It's a simple JSON file (with no nestings).

**Comment by lancejpollard** [comment]
You can publish the data as JSON as GitHub Pages if you wanted, it will allow you to keep the JSON API available for free, though not sure if you need any dynamic functionality, it would just be saved JSON files.

I would like to publish the Rig Veda as part of a collection of ancient texts across cultures, like [this one](https://seed.surf/text/tao-te-ching/chinese/101/1?pronunciation=pinyin) I have done for the Tao Te Ching (from WikiSource).

If you could provide a sample record from the JSON, that would be neat to see how it's structured for now, I didn't see that on the site. Also, where did you get the data?

**Comment by AninditaBasu** [comment]
I'm not comfortable sharing the data file itself on a public site like seed.surf 😞 

Here's a sample record:

```
{
    "mandal": 1,
    "sukta": 1,
    "sungby": "Madhuchchhanda Vaishwamitra",
    "sungbycategory": "human male",
    "sungfor": "Agni",
    "sungforcategory": "divine male",
    "meter": "Gayatri"
  },
```

I built the database myself, and the main reference was _Rig Veda Samhita, the English translation according to H. H. Wilson and the Bhashya of Sayanacharya, by Ravi Prakash Arya and K. L. Joshi_. Other books were also consulted.

**Comment by lancejpollard** [comment]
Ok thanks anyways!
