### ISSUE TITLE
Use of this Api

### ISSUE THREAD

**Issue by sandhya-2** [AninditaBasu/indica#8]
_Use this template if you have questions about this project. Don't forget to check our [documentation](https://aninditabasu.github.io/indica/index.html); we update them based on the questions we receive._

## My question

_What do you want to ask us? What are you trying to accomplish with these APIs?_
I am a developer and I want to use this Vedic Api in my app and web development project. I am a self learner. I am not able to view the Json data as your website is down. Please sir I need this to build an swift app and a website. I hope you will resolve it. Thank you. 

## I've already tried

_Help us help you by letting us know what you've already tried in your efforts to accomplish this. If you don't put anything here, we are likely to point you to the documentation :wink:_

I am getting the error as "404 error: The most un-favorite part of web navigation".

**Comment by AninditaBasu** [comment]
Hello @sandhya-2 

Thank you for your interest in these APIs.

The web service that hosts this API is no longer available to me under a free plan, and I don't yet have a budget for hosting the APIs elsewhere. Therefore, the API will remain unavailable this year at least, or till such time as I can allocate the money towards hosting.

I'm sorry if this upsets your learning plans. The best I can do is point you to some other APIs that are publicly available (and will remain available in the foreseeable future):
- https://developers.google.com/books
- https://api.nasa.gov/

Am hoping this helps.
